# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    dir: ./desktop-app
    cmds:
      - rm -rf /Applications/isitcorrect.app
      - wails build
      - mv ./build/bin/isitcorrect.app /Applications/