// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAnswer(arg1) {
  return window['go']['main']['App']['GenerateAnswer'](arg1);
}

export function GetRoomID() {
  return window['go']['main']['App']['GetRoomID']();
}

export function GetSelectionText() {
  return window['go']['main']['App']['GetSelectionText']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings() {
  return window['go']['main']['App']['SaveSettings']();
}

export function SetRoomID(arg1) {
  return window['go']['main']['App']['SetRoomID'](arg1);
}

export function SetSystemMessage() {
  return window['go']['main']['App']['SetSystemMessage']();
}

export function StartWsConnection(arg1, arg2) {
  return window['go']['main']['App']['StartWsConnection'](arg1, arg2);
}

export function StartWsHandler() {
  return window['go']['main']['App']['StartWsHandler']();
}
