// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAnswer(arg1:string):Promise<void>;

export function GetRoomID():Promise<string>;

export function GetSelectionText():Promise<string>;

export function IsConnected():Promise<boolean>;

export function LoadSettings():Promise<void>;

export function SaveSettings():Promise<void>;

export function SetRoomID(arg1:string):Promise<void>;

export function SetSystemMessage():Promise<void>;

export function StartWsConnection(arg1:string,arg2:string):Promise<void>;

export function StartWsHandler():Promise<void>;
