// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSelectionText() {
  return window['go']['main']['App']['GetSelectionText']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
